name: Bug Report
description: File a bug report
title: "[🐛]: "
labels: [bug]
assignees:
  - madooei
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue (report) for this bug?
      description: Please search [here](https://github.com/jhu-cs-ca-hiring/feedback/labels/bug) to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Also, if possible, please tell us what did you expect to happen? 
        And, how we might be able to reproduce the erronous behavior? (The steps to reproduce the error.)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant error output
      description: |
        Please copy and paste any relevant error output. This will be automatically formatted into code, so no need for backticks.
        
        Tip: If you know how to access your browser Developer Tool, you may find error messages in the browser console.
        We highly appreciate it if you provide those error messages. 
      render: shell
  - type: textarea
    id: other
    attributes:
      label: Anything else?
      description: |
        Screenshots? Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
